"""create vessels table

Revision ID: c2e2eafb2951
Revises:
Create Date: 2026-02-07 16:58:18.798039

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2e2eafb2951"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vessels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("imo_number", sa.String(), nullable=False),
        sa.Column("max_capacity", sa.Float(), nullable=False),
        sa.Column("current_reserved_capacity", sa.Float(), nullable=False),
        sa.Column("vessel_type", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "current_reserved_capacity <= max_capacity", name="check_capacity_limit"
        ),
        sa.CheckConstraint(
            "current_reserved_capacity >= 0", name="check_positive_capacity"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_active_vessels",
        "vessels",
        ["id"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index(
        op.f("ix_vessels_imo_number"), "vessels", ["imo_number"], unique=True
    )
    op.create_index(
        op.f("ix_vessels_vessel_type"), "vessels", ["vessel_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vessels_vessel_type"), table_name="vessels")
    op.drop_index(op.f("ix_vessels_imo_number"), table_name="vessels")
    op.drop_index(
        "idx_active_vessels",
        table_name="vessels",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_table("vessels")
    # ### end Alembic commands ###
